on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
#set up R
      - name: Install packages
        run:
          R -e 'install.packages("rMR")'
          R -e 'library(devtools)'
          R -e 'install.packages("remotes")'
          R -e 'library(remotes)'
          R -e 'remotes::install_github("eco4cast/neon4cast", auth_token = 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)'
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        run: Rscript Main.R 
